# Generated by Django 5.1.4 on 2024-12-20 08:02

import HikingTrails.Trails.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0004_meetingphotos_uploaded_at_meetingphotos_uploaded_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingphotos',
            name='image',
            field=models.ImageField(upload_to='meeting_photos/', validators=[HikingTrails.Trails.validators.validate_image]),
        ),
    ]
