# Generated by Django 5.1.4 on 2024-12-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hikers', '0002_hiker_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiker',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
