# Generated by Django 5.1.3 on 2024-11-23 15:55

import django.db.models.deletion
from django.db import migrations, models

import HikingTrails.Trails.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('Hikers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('length', models.FloatField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='trail_images/',
                                            validators=[HikingTrails.Trails.validators.validate_image])),
                ('description', models.TextField(help_text='Enter a description of the trail')),
                ('elevation_gain', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hiker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trails',
                                            to='Hikers.hiker')),
            ],
        ),
    ]
