# Generated by Django 5.1.3 on 2024-11-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Trails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trails',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Intermediate', 'Intermediate'), ('Uphill', 'Uphill')],
                                   default='Easy'),
        ),
    ]
