# Generated by Django 5.1.3 on 2024-11-25 15:45

import HikingTrails.Trails.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trails', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trails',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/trail_images/', validators=[HikingTrails.Trails.validators.validate_image]),
        ),
    ]
