# Generated by Django 5.1.3 on 2024-11-25 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trails', '0004_alter_trails_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trails',
            name='difficulty',
            field=models.TextField(choices=[('Easy', 'Easy'), ('Intermediate', 'Intermediate'), ('Uphill', 'Uphill')], default='Easy'),
        ),
    ]
