# Generated by Django 5.1.3 on 2024-12-01 07:51

import HikingTrails.Trails.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trails', '0006_alter_trails_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trails',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media', validators=[HikingTrails.Trails.validators.validate_image]),
        ),
    ]
