# Generated by Django 5.1.3 on 2024-12-03 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trails', '0009_rename_hiker_comment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrailPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hiker_images/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='Trails.trails')),
            ],
        ),
    ]
