# Generated by Django 5.1.3 on 2024-12-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trails', '0010_trailphotos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailphotos',
            name='image',
            field=models.ImageField(upload_to='trail_images/'),
        ),
    ]
